/*CREATE TABLE COLOR*/
IF (OBJECT_ID('COLOR')) > 0
BEGIN
	DROP TABLE [COLOR]
END;
CREATE TABLE [dbo].[COLOR](
	ID INT NOT NULL IDENTITY(1,1),	
	NM_COLOR VARCHAR(150) NOT NULL,	
	DT_CREATE DATETIME NOT NULL,
	DT_ALTER DATETIME NOT NULL
)

/*PRIMARY KEY*/
ALTER TABLE [dbo].[COLOR] ADD CONSTRAINT PK_COLOR PRIMARY KEY CLUSTERED ([ID] ASC)

/*INDEX*/
CREATE INDEX ix_COLOR ON [dbo].[COLOR](ID)

INSERT INTO [dbo].[COLOR](NM_COLOR, DT_CREATE, DT_ALTER)
VALUES('blue', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[COLOR](NM_COLOR, DT_CREATE, DT_ALTER)
VALUES('green', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[COLOR](NM_COLOR, DT_CREATE, DT_ALTER)
VALUES('red', GETDATE(), GETDATE())