/*CREATE TABLE DAY*/
IF (OBJECT_ID('DAY')) > 0
BEGIN
	DROP TABLE [DAY]
END;
CREATE TABLE [dbo].[DAY](
	ID INT NOT NULL IDENTITY(1,1),
	ID_RESPONDENT INT NOT NULL,
	ID_MONTH INT NOT NULL,
	ID_COLOR INT NOT NULL,
	DT_DAY DATE NOT NULL,
	DT_BEGIN_1 TIME NOT NULL,
	DT_END_1 TIME NOT NULL,
	DT_BEGIN_2 TIME NOT NULL,
	DT_END_2 TIME NOT NULL,
	DT_CREATE DATETIME NOT NULL,
	DT_ALTER DATETIME NOT NULL
)

/*PRIMARY KEY*/
ALTER TABLE [dbo].[DAY] ADD CONSTRAINT PK_DAY PRIMARY KEY CLUSTERED ([ID] ASC)

/*FOREIGN KEY*/
ALTER TABLE [dbo].[DAY] ADD CONSTRAINT FK_DAY_RESPONDENT FOREIGN KEY (ID_RESPONDENT) REFERENCES [dbo].[RESPONDENT] (ID)
ALTER TABLE [dbo].[DAY] ADD CONSTRAINT FK_DAY_MONTH FOREIGN KEY (ID_MONTH) REFERENCES [dbo].[MONTH] (ID)
ALTER TABLE [dbo].[DAY] ADD CONSTRAINT FK_DAY_COLOR FOREIGN KEY (ID_COLOR) REFERENCES [dbo].[COLOR] (ID)

/*INDEX*/
CREATE INDEX ix_DAY ON [dbo].[DAY](ID)