/*CREATE TABLE MONTH*/
IF (OBJECT_ID('MONTH')) > 0
BEGIN
	DROP TABLE [MONTH]
END;
CREATE TABLE [dbo].[MONTH](
	ID INT NOT NULL IDENTITY(1,1),	
	NM_MONTH VARCHAR(150) NOT NULL,	
	DT_CREATE DATETIME NOT NULL,
	DT_ALTER DATETIME NOT NULL
)

/*PRIMARY KEY*/
ALTER TABLE [dbo].[MONTH] ADD CONSTRAINT PK_MONTH PRIMARY KEY CLUSTERED ([ID] ASC)

/*INDEX*/
CREATE INDEX ix_MONTH ON [dbo].[MONTH](ID)

INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('JANEIRO', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('FEVEREIRO', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('MARÇO', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('ABRIL', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('MAIO', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('JUNHO', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('JULHO', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('AGOSTO', GETDATE(), GETDATE())
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('SETEMBRO', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('OUTUBRO', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('NOVEMBRO', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[MONTH](NM_MONTH, DT_CREATE, DT_ALTER)
VALUES('DEZEMBRO', GETDATE(), GETDATE())