/*CREATE TABLE USERTYPE*/
IF (OBJECT_ID('USERTYPE')) > 0
BEGIN
	DROP TABLE [USERTYPE]
END;
CREATE TABLE [dbo].[USERTYPE](
	ID INT NOT NULL IDENTITY(1,1),	
	NM_TYPE VARCHAR(150) NOT NULL,	
	DT_CREATE DATETIME NOT NULL,
	DT_ALTER DATETIME NOT NULL
)

/*PRIMARY KEY*/
ALTER TABLE [dbo].[USERTYPE] ADD CONSTRAINT PK_USERTYPE PRIMARY KEY CLUSTERED ([ID] ASC)

/*INDEX*/
CREATE INDEX ix_USERTYPE ON [dbo].[USERTYPE](ID)

INSERT INTO [dbo].[USERTYPE](NM_TYPE, DT_CREATE, DT_ALTER)
VALUES('ADMINISTRADOR', GETDATE(), GETDATE())
GO
INSERT INTO [dbo].[USERTYPE](NM_TYPE, DT_CREATE, DT_ALTER)
VALUES('COMUM', GETDATE(), GETDATE())