/*CREATE TABLE USER*/
IF (OBJECT_ID('USER')) > 0
BEGIN
	DROP TABLE [USER]
END;
CREATE TABLE [dbo].[USER](
	ID INT NOT NULL IDENTITY(1,1),
	ID_USERTYPE INT NOT NULL,
	NM_USER VARCHAR(150) NOT NULL,
	NM_EMAIL VARCHAR(150) NOT NULL,
	NM_PASSWORD CHAR(32) NOT NULL,
	DT_CREATE DATETIME NOT NULL,
	DT_ALTER DATETIME NOT NULL
)

/*PRIMARY KEY*/
ALTER TABLE [dbo].[USER] ADD CONSTRAINT PK_USER PRIMARY KEY CLUSTERED ([ID] ASC)

/*FOREIGN KEY*/
ALTER TABLE [dbo].[USER] ADD CONSTRAINT FK_USER_USERTYPE FOREIGN KEY (ID_USERTYPE) REFERENCES [dbo].[USERTYPE] (ID)

/*INDEX*/
CREATE INDEX ix_USER ON [dbo].[USER](ID)